### ISSUE TITLE
Typo in https://www.mskog.com/posts/autocomplete-in-ruby-on-rails-using-stimulus/

### ISSUE THREAD

**Issue by maren-myc** [mskog/autocomplete_stimulus_example#1]
Hey @mskog,

thanks a lot for your tutorial!

I'm currently trying it out and recognized while debugging (and thanks to your code here on github) that there is one typo in the code examples in your blog. 
In `application.js`  
`const context = require.context("../stimulus/controllers", true, /\\.js$/);` should be
`const context = require.context("../stimulus/controllers", true, /\.js$/);` 

If not the controller is not loaded and can't be connected. It would be cool if you could change it.
Thanks a lot :)

**Comment by mskog** [comment]
I've fixed the typo. Thanks!
