### ISSUE TITLE
@algolia/autocomplete.js

### ISSUE THREAD

**Issue by justinallenmarsh** [mskog/autocomplete_stimulus_example#3]
I used this guide a year back to make an autocomplete bar. It was the most straight forward stimulus guide to get autocomplete working for a new programmer.

I had upgraded my app to rails 7 and ESBUILD and ran into issues regarding the autocomplete.js being depreciated and is now moved to a v1 @algolia/autocomplete.js.

It seems like the new library might be quite different from the old one.

**Comment by johanla0** [comment]
@jmarsh24, not very different, you just `import { autocomplete } from '@algolia/autocomplete-js';`
Then you will need to create a config object, pay attention to stimulus targets and values, YMMW
The docs are somewhat clear about that: https://www.algolia.com/doc/ui-libraries/autocomplete/core-concepts/basic-configuration-options/
```
const config = {
  container: this.searchContainerTarget,
  placeholder: this.placeholderValue,
  getSources({ query }) {
    return fetch(`/search.json?s=${query}`)
      .then((response) => response.json())
      .then((records) => {
        return [
          {
            sourceId: 'records',
            getItems() {
              return records;
            },
            getItemUrl({ item }) {
              return item.url;
            },
            getItemInputValue({ item }) {
              return item.name;
            },
            templates: {
              item({ item }) {
                return item.name;
              },
              noResults() {
                return 'No results';
              },
            },
          },
        ]
      })
  },
}
```
In the end of the `connect()` function don't forget to call the `autocomplete(config);`

**Comment by BenCh94** [comment]
@johanla0 migrating to this style setup caused some issues for me in rails 7, I'm running into a reference error:
   `Error connecting controller

    ReferenceError: process is not defined
    at invariant (invariant.js:7:9)
    at getDefaultOptions (getDefaultOptions.js:85:3)
    at autocomplete.js:38:12
    at reactive (createReactiveWrapper.js:5:21)
    at autocomplete (autocomplete.js:37:15)
    at extended.connect (autocomplete_controller-71a177cf1c6965fe70a74133af4987def29574f700c525af7f88998bd13a0727.js:58:9)
    at Context.connect (stimulus.js? [sm]:1379:29)
    at Module.connectContextForScope (stimulus.js? [sm]:1549:17)
    at stimulus.js? [sm]:1936:42
    at Array.forEach (<anonymous>)`

From what I understand process is a javascript constant used in backend languages like node.js, Is there a way to get this working in stimulus?
